### ISSUE TITLE
Transperency

### ISSUE THREAD

**Issue by a268-Beefy** [cr4ckp0t/ElvUI_MicroMenuDatatext#1]
Could you please make an option to setup background? As you can see it is useing global transperency and it is quite unreadable.
![WoWScrnShot_012620_151218](https://user-images.githubusercontent.com/58666790/73299178-c123f500-421f-11ea-85a9-87a7cc306024.jpg)

Transparency is handled by ElvUI directly.
YES but it is GLOBAL function and it changes also chat frames and other parts of ElvUI.
![WoWScrnShot_012820_224539](https://user-images.githubusercontent.com/58666790/73299443-40b1c400-4220-11ea-9ac8-2c699472e4e4.jpg)

**Comment by cr4ckp0t** [comment]
I would have to look into the API more since this addon just uses WOW's EasyMenu system for this. It may only be possible to set the alpha (transparency) globally.
